import numpy as np
import pandas as pd

from mdx2.report._stats import _calc_isoavg


def prepare_table(hkl_table, crystal, symmetry, bin_width=0.01):
    """Add missing columns to the hkl_table, return a dataframe.

    - intensity, intensity_error, and multiplicity may be missing if the hkl_table was generated by mdx2.reintegrate.
    - s is usually missing.
    - is_reflection: a flag for voxels centered on Bragg reflections.
    - intensity_iso: robust isotropic average of intensity as a function of s.
    """
    if hasattr(hkl_table, "s"):
        s = hkl_table.s
    else:
        UB = crystal.ub_matrix
        s = UB @ np.stack((hkl_table.h, hkl_table.k, hkl_table.l))
        s = np.sqrt(np.sum(s * s, axis=0))
    if hasattr(hkl_table, "intensity"):
        intensity = hkl_table.intensity
        intensity_error = hkl_table.intensity_error
    else:  # mdx2.reintegrate saves counts intead, need to compute intensity and error
        intensity = (hkl_table.counts - hkl_table.background_counts) / hkl_table.scale
        intensity_error = np.sqrt(hkl_table.counts) / hkl_table.scale
    if hasattr(hkl_table, "count"):
        multiplicity = hkl_table.count
    else:
        multiplicity = hkl_table.multiplicity

    # calculate bin edges
    smax = s.max()
    bin_edges = np.linspace(0, smax, int(smax / bin_width) + 1)

    column_data = {
        "h": hkl_table.h,
        "k": hkl_table.k,
        "l": hkl_table.l,
        "s": s,
        "intensity": intensity,
        "intensity_error": intensity_error,
        "multiplicity": multiplicity,
    }

    has_split_datasets = hasattr(hkl_table, "group_0_intensity") and hasattr(hkl_table, "group_1_intensity")
    if has_split_datasets:
        column_data["group_0_intensity"] = hkl_table.group_0_intensity
        column_data["group_1_intensity"] = hkl_table.group_1_intensity

    df = pd.DataFrame(column_data)

    df.dropna(subset=["intensity"], inplace=True)

    # calculate a robust isotropic average
    s_iso, intensity_iso = _calc_isoavg(df, bin_edges=bin_edges)

    df["intensity_iso"] = np.interp(df["s"], s_iso, intensity_iso)
    df["intensity_sub"] = df["intensity"] - df["intensity_iso"]

    if has_split_datasets:
        df["group_0_intensity_sub"] = df["group_0_intensity"] - df["intensity_iso"]
        df["group_1_intensity_sub"] = df["group_1_intensity"] - df["intensity_iso"]

    # flag reflections
    def _is_integer(h):
        return (h.round() - h).abs() < 0.00001

    def _is_reflection(symmetry, h, k, l):
        return _is_integer(h) & _is_integer(k) & _is_integer(l) & symmetry.is_reflection(h, k, l)

    df["is_reflection"] = _is_reflection(symmetry, df.h, df.k, df.l)

    return df


def calc_intensity_statistics(df, bin_width=0.01, exclude_bragg=False):
    # calculate bin edges
    smax = df["s"].max()
    bin_edges = np.linspace(0, smax, int(smax / bin_width) + 1)

    if exclude_bragg:
        df = df[~df["is_reflection"]]

    def rmsavg(x):
        return np.sqrt(np.mean(x * x))

    # compute statistics in each bin
    s_bins = pd.cut(df["s"], bins=bin_edges)
    df_isoavg = df.groupby(s_bins, observed=False).agg(
        s=("s", "mean"),
        # count=("s", "count"),
        intensity_iso=("intensity_iso", "mean"),
        # intensity_mean=("intensity", "mean"),
        intensity_sub_rms=("intensity_sub", rmsavg),
        intensity_error_rms=("intensity_error", rmsavg),
    )

    return df_isoavg


def calc_correlation_of_half_datasets(df, bin_width=0.01, exclude_bragg=False):
    df = df.dropna(subset=["group_0_intensity", "group_1_intensity"])

    if exclude_bragg:
        df = df[~df["is_reflection"]]

    def rmsavg(x):
        return np.sqrt(np.mean(x * x))

    def cc_est(intensity, intensity_error):
        """Rough estimate of the cc 1/2 based on signal-to-noise."""
        irms = rmsavg(intensity)
        erms = rmsavg(intensity_error)
        cc_est = (irms**2 - erms**2) / (irms**2 + erms**2)
        cc_est = np.clip(cc_est, 0, 1)
        return cc_est

    # compute statistics in each bin
    smax = df["s"].max()
    bin_edges = np.linspace(0, smax, int(smax / bin_width) + 1)
    s_bins = pd.cut(df["s"], bins=bin_edges)

    df_isoavg = df.groupby(s_bins, observed=False).agg(
        s=("s", "mean"),
        correlation=("group_0_intensity_sub", lambda x: x.corr(df.loc[x.index, "group_1_intensity_sub"])),
        snr_limit=("intensity_sub", lambda x: cc_est(x, df.loc[x.index, "intensity_error"])),
    )

    return df_isoavg
